### ISSUE TITLE
Error in exporting

### ISSUE THREAD

**Issue by Samaalir** [tmcgee/cmv-widgets#120]
Hello, I use the export widget and i get an error message when i choose to export map as a shapefile
`Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.setUint8 (<anonymous>)
    at Object.t.exports [as structure] (http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:1:17853)
    at r (http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:1:23396)
    at http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:1:24262
    at Array.forEach (native)
    at Object.t.exports [as zip] (http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:1:24190)
    at Object.<anonymous> (http://localhost:50537/Scripts/arcgis/gis/dijit/Export.js:534:40)
    at http://localhost:50537/Scripts/arcgis/3.20/init.js:63:277
    at ia (http://localhost:50537/Scripts/arcgis/3.20/init.js:28:8)
    at http://localhost:50537/Scripts/arcgis/3.20/init.js:28:263`

**Comment by tmcgee** [comment]
@Samaalir this appears to be an issue in the [shp-write](https://github.com/mapbox/shp-write) library. Not clear on the issue but it might be data (non-english characters?) that isn't supported by that library. As a test, you may want to try exporting the same data from your application as geojson and then use that geojson file at [geojson.io](http://geojson.io) and save as a shape file. That site uses nearly the same version as I use with the Export widget. Let me know how it goes.

**Comment by Samaalir** [comment]
hello @tmcgee , thank you for your help, I will explain more to you, actually your widget works well in exporting shapefiles ( I have juste tested it with a different layer and it works) I think the problem is with some layers that I don"t the cause, here is the problem ( I have unminifiyed the shp library-file )
`Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.setUint8 (<anonymous>)
    at Object.t.exports [as structure] (http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:685:19)
    at r (http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:886:27)
    at http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:932:74
    at Array.forEach (native)
    at Object.t.exports [as zip] (http://localhost:50537/Scripts/arcgis/gis/dijit/Export/lib/shpwrite-0.2.6.min.js:931:59)
    at Object.<anonymous> (http://localhost:50537/Scripts/arcgis/gis/dijit/Export.js:534:44)
    at http://localhost:50537/Scripts/arcgis/3.20/init.js:63:277
    at ia (http://localhost:50537/Scripts/arcgis/3.20/init.js:28:8)
    at http://localhost:50537/Scripts/arcgis/3.20/init.js:28:263
t.exports @ VM4240 shpwrite-0.2.6.min.js:685
r @ VM4240 shpwrite-0.2.6.min.js:886
(anonymous) @ VM4240 shpwrite-0.2.6.min.js:932
t.exports @ VM4240 shpwrite-0.2.6.min.js:931
(anonymous) @ Export.js:534
(anonymous) @ init.js:63
ia @ init.js:28
(anonymous) @ init.js:28
ja @ init.js:28
ga @ init.js:28
k @ init.js:30
(anonymous) @ init.js:35
`

**Comment by tmcgee** [comment]
@Samaalir If it works with some layers but not others, I think that further supports my comment that it is specific to the data. Since line 685 appears to be attempting to convert a date, perhaps the problem is a date field with an invalid date or a date stored in an unexpected format?

**Comment by Samaalir** [comment]
Yes I think the problem is with my date field, I have declared it datetime2(to be known by arcgis as a date field), so the result that I have got records like "01/01/1970 00:00"

**Comment by tmcgee** [comment]
For any export, your data is converted first to geojson before the conversion to shape file. So I suggest you export to geojson and look at the resulting data or try exporting that geojson as a shape file from the geojson.io web application. The last step is to see if the same error occurs. I suspect it will.

**Comment by Samaalir** [comment]
Ok thank you for your precious help and time
